=== dante7qx/java-world/zan-hr/database/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.hna.net/dmt/schema"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.hna.net/dmt/schema">

	<xsd:annotation>
		<xsd:documentation>@version 0.9</xsd:documentation>
		<xsd:documentation>java -Dfile.encoding=UTF-8 -cp d:\sun\java\lib\tools.jar com.sun.tools.internal.xjc.Driver -npa -no-header datamodel.xsd</xsd:documentation>
		<xsd:documentation>xjc -npa -no-header datamodel.xsd
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="schema" type="Schema">
		<xsd:annotation>
			<xsd:documentation>数据模型，根元素。</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:complexType name="Schema">
		<xsd:annotation>
			<xsd:documentation>数据库或者模式</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="table" type="Table" minOccurs="0"
				maxOccurs="unbounded">
			</xsd:element>
			<xsd:element name="view" type="View" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			<xsd:element name="sheet" type="Sheet" minOccurs="0"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>辅助图表页</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="version" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="vendor" type="Vendor" use="optional">
			<xsd:annotation>
				<xsd:documentation>厂商</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="locale" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>语区，所有title和note可以应用该种语言</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>数据库名或者模式名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="dsn" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>在IDE中的数据源名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="domain" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>业务域，用于包名前缀如：com.app</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>代码生成路径</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="geometry" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>图形参数，用于可视化显示</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Table">
		<xsd:annotation>
			<xsd:documentation>数据表定义</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="column" type="Column" minOccurs="1"
				maxOccurs="unbounded">
			</xsd:element>
			<xsd:element name="index" type="Index" minOccurs="0"
				maxOccurs="unbounded">
			</xsd:element>
			<xsd:element name="foreignKey" type="ForeignKey"
				minOccurs="0" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>表名，一般使用大写字母+下划线写法</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="javaName" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Java实体Bean名，可选，使用默认机制从name生成
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="title" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					业务名称，可使用中文或本地语言，必选
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="module" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					模块名，对包名有影响，若为user，则包名为：com.app.user
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="list" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有列表页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="tree" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否具有树形页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="detail" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有明细页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="create" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有增加页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="update" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有更新页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="delete" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有删除页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="note" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					表的注释，可使用本地语言描述业务含义
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="geometry" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>图形化参数，用于IDE显示和编辑</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="collapsed" type="xsd:boolean"
			default="false" use="optional">
			<xsd:annotation>
				<xsd:documentation>折叠显示与否</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Column">
		<xsd:annotation>
			<xsd:documentation>列的定义。</xsd:documentation>
		</xsd:annotation>
		<xsd:choice minOccurs="0" maxOccurs="1">
			<xsd:element name="sequence" type="Sequence" minOccurs="0"
				maxOccurs="1">
			</xsd:element>
			<xsd:element name="state" type="State" minOccurs="0"
				maxOccurs="unbounded">
			</xsd:element>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>列名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="title" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>列的业务名称，必选</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="type" type="Type" use="required">
			<xsd:annotation>
				<xsd:documentation>
					列的数据库类型。当type是ENUM时，需指定状态列表
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="size" type="xsd:int" use="optional"
			default="0">
			<xsd:annotation>
				<xsd:documentation>
					数据类型的长度，如类型是varchar，长度为20
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="scale" type="xsd:int" use="optional"
			default="0">
			<xsd:annotation>
				<xsd:documentation>
					类型的精度，如类型是decimal，长度是10，精度是2，表示最多两位小数
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="primaryKey" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否是主键，默认是false</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="notNull" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否非空，默认是false</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="javaName" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					对应的Java实体Bean的字段名，要符合Java命名规范。可选，通过name以默认机制生成
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="javaType" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					对应的Java类型，可选，通过type自动映射
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="invisiable" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否不可显示，如审计所用的创建、更新时间等，是不需要显示的。
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="readonly" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否不可更改，比如用户的是否系统属性，是不可修改的。</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="sorting" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否在列表上是否参与排序。</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="filtering" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否参与到查询过滤条件中。</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="note" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>列的业务备注</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Index">
		<xsd:annotation>
			<xsd:documentation>索引的定义</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="column" type="xsd:string" minOccurs="1"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>索引包含的列</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>索引名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="unique" type="xsd:boolean" use="required">
			<xsd:annotation>
				<xsd:documentation>是否是唯一性索引</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ForeignKey">
		<xsd:annotation>
			<xsd:documentation>外键定义</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="reference" type="Reference" minOccurs="1"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>外键的引用定义</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>外键名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="foreignTable" type="xsd:string"
			use="required">
			<xsd:annotation>
				<xsd:documentation>外键所引用的表</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="real" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否物理存在</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="constraint" type="Constraint" use="optional"
			default="1..1">
			<xsd:annotation>
				<xsd:documentation>约束类型</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="note" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>注释</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="geometry" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>图形参数，用于IDE显示和编辑</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="Type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="VARCHAR"></xsd:enumeration>
			<xsd:enumeration value="INTEGER"></xsd:enumeration>
			<xsd:enumeration value="BOOLEAN"></xsd:enumeration>
			<xsd:enumeration value="ENUM"></xsd:enumeration>
			<xsd:enumeration value="NUMBER"></xsd:enumeration>
			<xsd:enumeration value="CHAR"></xsd:enumeration>
			<xsd:enumeration value="DATE"></xsd:enumeration>
			<xsd:enumeration value="TIME"></xsd:enumeration>
			<xsd:enumeration value="TIMESTAMP"></xsd:enumeration>
			<xsd:enumeration value="BLOB"></xsd:enumeration>
			<xsd:enumeration value="CLOB"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Vendor">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="oracle"></xsd:enumeration>
			<xsd:enumeration value="mysql"></xsd:enumeration>
			<xsd:enumeration value="sqlserver"></xsd:enumeration>
			<xsd:enumeration value="db2"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Constraint">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="1..1"></xsd:enumeration>
			<xsd:enumeration value="1..n"></xsd:enumeration>
			<xsd:enumeration value="m..1"></xsd:enumeration>
			<xsd:enumeration value="m..n"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Reference">
		<xsd:annotation>
			<xsd:documentation>外键的引用定义</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="local" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>本表列名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="foreign" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>父表列名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>


	<xsd:complexType name="Sequence">
		<xsd:annotation>
			<xsd:documentation>编号生成机制的定义</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="length" type="xsd:int" use="optional"
			default="0">
			<xsd:annotation>
				<xsd:documentation>编号的长度</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="prefix" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>前缀，可选</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="suffix" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>后缀，可选</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="fetchSize" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>编号预取集合的大小，一般在1-10000之间</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="State" mixed="true">
		<xsd:annotation>
			<xsd:documentation>枚举类型列的定义</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="value" type="xsd:byte" use="required">
			<xsd:annotation>
				<xsd:documentation>枚举值</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>


	<xsd:complexType name="Sheet">
		<xsd:annotation>
			<xsd:documentation>辅助图表页</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="table" type="TableRef" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>页名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="TableRef">
		<xsd:annotation>
			<xsd:documentation>数据表引用</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>数据表名</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="geometry" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>图形化参数，用于IDE显示和编辑</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="collapsed" type="xsd:boolean"
			default="false" use="optional">
			<xsd:annotation>
				<xsd:documentation>折叠显示与否</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="View">
		<xsd:annotation>
			<xsd:documentation>视图定义</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="column" type="xsd:string" minOccurs="1"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>View包含的列</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>表名，一般使用大写字母+下划线写法</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="table" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="javaName" type="xsd:string"
			use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Java实体Bean名，可选，使用默认机制从name生成
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="title" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					业务名称，可使用中文或本地语言，必选
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="module" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					模块名，对包名有影响，若为user，则包名为：com.app.user
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="list" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有列表页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="tree" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation>是否具有树形页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="detail" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有明细页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="create" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有增加页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="update" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有更新页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="delete" type="xsd:boolean" use="optional"
			default="true">
			<xsd:annotation>
				<xsd:documentation>是否具有删除页面</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="note" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					表的注释，可使用本地语言描述业务含义
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="geometry" type="xsd:string"
			use="optional">
			<xsd:annotation>
				<xsd:documentation>图形化参数，用于IDE显示和编辑</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="collapsed" type="xsd:boolean"
			default="false" use="optional">
			<xsd:annotation>
				<xsd:documentation>折叠显示与否</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== dante7qx/java-world/zan-hr/database/datamodel_hr.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="datamodel.xsl"?>
<schema name="" domain="com.epolleo" xmlns="http://www.hna.net/dmt/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hna.net/dmt/schema datamodel.xsd" >
	
	<table name="P_Att" javaName="" title="附件表" module="pub.att" geometry="30,30,172,116" collapsed="false">
        <column name="Id" title="编号" type="INTEGER" primaryKey="true" />
        <column name="LotId" title="附件批号" type="VARCHAR" size="64" />
        <column name="Type" title="类型" type="VARCHAR" size="128"/>
        <column name="Description" title="附件描述" type="VARCHAR" size="512"/>
        <column name="Path" title="附件路径" type="VARCHAR" size="512"/>
        <column name="UpdateBy" title="更新人" type="VARCHAR" size="32"/>
        <column name="UpdateDate" title="更新时间" type="TIMESTAMP"/>
    </table>
	
	<table name="hr_code_dict" module="hr.dictmnt" javaName="CodeDict" title="基础数据字典表">
		<column name="Id" title="Id" type="INTEGER" primaryKey="true" />
		<column name="Type" title="类型" type="VARCHAR" size="16" />
		<column name="TypeName" title="类型名称" type="VARCHAR" size="8" />
		<column name="Code" title="编码" type="VARCHAR" size="16" />
		<column name="Value" title="名称" type="VARCHAR" size="16" />
		<column name="ShowOrder" title="显示顺序" type="INTEGER" />
		<column name="UpdateBy" title="更新人" type="VARCHAR" size="32"/>
        <column name="UpdateDate" title="更新时间" type="TIMESTAMP"/>
	</table>
	
	<table name="hr_employee" title="员工" module="hr.employee" javaName="Employee" geometry="887,533,185,168" collapsed="false">
		<column name="Id" title="员工Id" type="INTEGER" primaryKey="true" />
		<column name="Code" title="员工编号" type="VARCHAR" size="64" />
		<column name="ChnName" title="员工名称" type="VARCHAR" size="64" />
		<column name="EngName" title="员工英文名称" type="VARCHAR" size="64" />
		<column name="UsedName" title="员工曾用名" type="VARCHAR" size="64" />
		
		<column name="IdNum" title="身份证号" type="VARCHAR" size="18" />
		<column name="Birthday" title="出生日期" type="DATE" />
		<column name="Gen" title="性别" type="ENUM">
			<state value="1">男</state>
			<state value="2">女</state>
		</column>
		<column name="Recruitment" title="籍贯" type="VARCHAR" size="32" />
		<column name="Horoscope" title="星座" type="ENUM">
			<state value="10">白羊座</state>
			<state value="20">金牛座</state>
			<state value="30">双子座</state>
			<state value="40">巨蟹座</state>
			<state value="50">狮子座</state>
			<state value="60">处女座</state>
			<state value="70">天秤座</state>
			<state value="80">天羯座</state>
			<state value="90">射手座</state>
			<state value="100">摩羯座</state>
			<state value="110">水瓶座</state>
			<state value="120">双鱼座</state>
		</column>
		<column name="Household" title="户口性质" type="ENUM">
			<state value="10">城镇</state>
			<state value="20">农村</state>
		</column>
		<column name="Politics" title="政治面貌" type="ENUM">
			<state value="10">党员</state>
			<state value="20">团员</state>
			<state value="30">群众</state>
		</column>
		<column name="Marriage" title="婚姻状况" type="ENUM">
			<state value="10">未婚</state>
			<state value="20">已婚</state>
		</column>
		<column name="Phone" title="联系电话" type="VARCHAR" size="32" />
		<column name="Email" title="电子邮箱" type="VARCHAR" size="64" />
		<column name="HealthValid" title="健康证明有效期" type="DATE" />
		<column name="Education" title="学历" type="ENUM">
			<state value="10">中专</state>
			<state value="20">专科</state>
			<state value="30">本科</state>
			<state value="40">硕士</state>
			<state value="50">博士</state>
		</column>
		<column name="Major" title="专业" type="VARCHAR" size="64" />
		<column name="GraduateInstitution" title="毕业院校" type="VARCHAR" size="128" />
		<column name="GraduateDate" title="毕业时间" type="DATE" />
		<column name="LanguageSkill" title="语种" type="ENUM">
			<state value="10">英语</state>
			<state value="20">韩语</state>
			<state value="30">日语</state>
			<state value="40">法语</state>
			<state value="50">西班牙语</state>
			<state value="60">葡萄牙语</state>
		</column>
		<column name="UrgencyLinkman" title="紧急联系人/电话" type="VARCHAR" size="512" />
		<column name="FileLocation" title="档案存放地" type="VARCHAR" size="1024" />
		<column name="HouseholdLocation" title="户口所在地" type="VARCHAR" size="1024" />
		<column name="Dwell" title="居住地址" type="VARCHAR" size="1024" />
		<column name="AttLotId" title="附件号" type="VARCHAR" size="64" />
		<column name="IsActive" title="是否生效" type="BOOLEAN" />
		<column name="IsDelete" title="是否删除" type="BOOLEAN" />
		<column name="createUser" title="创建人" type="VARCHAR" size="32" />
		<column name="createTime" title="创建时间" type="TIMESTAMP" />
		<column name="updateUser" title="更新人" type="VARCHAR" size="32" />
		<column name="updateTime" title="更新时间" type="TIMESTAMP" />
	</table>
	
	<table name="hr_employee_certificate" title="员工资格、职称证书" module="hr.employee" javaName="EmployeeCertificate" geometry="887,533,185,168" collapsed="false">
		<column name="Id" title="编号" type="INTEGER" primaryKey="true" />
		<column name="EmployeeId" title="员工Id" type="INTEGER" />
		<column name="Name" title="证书名称" type="VARCHAR" size="128" />
		<column name="SignDate" title="签发日期" type="DATE" />
		<column name="ExpDate" title="失效日期" type="DATE" />
		<column name="AttLotId" title="附件号" type="VARCHAR" size="64" />
		<column name="IsDelete" title="是否删除" type="BOOLEAN" />
		<column name="createUser" title="创建人" type="VARCHAR" size="32" />
		<column name="createTime" title="创建时间" type="TIMESTAMP" />
		<column name="updateUser" title="更新人" type="VARCHAR" size="32" />
		<column name="updateTime" title="更新时间" type="TIMESTAMP" />
	</table>
	
	<table name="hr_employee_work" title="员工工作信息" module="hr.employee" javaName="EmployeeWork" geometry="887,533,185,168" collapsed="false">
		<column name="Id" title="编号" type="INTEGER" primaryKey="true" />
		<column name="EmployeeId" title="员工Id" type="INTEGER" />
		<column name="WorkPlaceId" title="工作地点" type="INTEGER" />
		<column name="Company" title="入职公司" type="INTEGER" />
		<column name="Dept" title="入职部门" type="INTEGER" />
		<column name="Post" title="入职岗位" type="INTEGER" />
		<column name="CapacityLevel" title="能力级别" type="ENUM">
			<state value="10">初级</state>
			<state value="20">中级</state>
			<state value="30">高级</state>
			<state value="40">资深</state>
		</column>
		<column name="EntrantDate" title="入职日期" type="DATE" />
		<column name="Type" title="员工类型" type="ENUM">
			<state value="10">正式员工</state>
			<state value="20">实习员工</state>
			<state value="30">临时工</state>
		</column>
		<column name="TrialPeriod" title="试用期" type="ENUM">
			<state value="1">无</state>
			<state value="2">有</state>
		</column>
		<column name="ContractDeadline" title="合同期限" type="ENUM">
			<state value="10">1</state>
			<state value="20">2</state>
			<state value="30">3</state>
		</column>
		<column name="ContractType" title="合同类型" type="ENUM">
			<state value="10">固定期限</state>
			<state value="20">无固定期限</state>
		</column>
		<column name="ContractStartDate" title="合同期限开始时间" type="DATE" />
		<column name="ContractEndDate" title="合同期限结束时间" type="DATE" />
		<column name="TrialDeadline" title="试用期结束日期" type="DATE" />
		<column name="PracticeStartDate" title="实习期限开始时间" type="DATE" />
		<column name="PracticeEndDate" title="实习期限结束时间" type="DATE" />
		<column name="ParttimeStartDate" title="实习期限开始时间" type="DATE" />
		<column name="ParttimeEndDate" title="实习期限结束时间" type="DATE" />
		<column name="createUser" title="创建人" type="VARCHAR" size="32" />
		<column name="createTime" title="创建时间" type="TIMESTAMP" />
		<column name="updateUser" title="更新人" type="VARCHAR" size="32" />
		<column name="updateTime" title="更新时间" type="TIMESTAMP" />
	</table>
	
	<table name="hr_employee_relation" title="员工家属信息" module="hr.employee" javaName="EmployeeRelation" geometry="887,533,185,168" collapsed="false">
		<column name="Id" title="编号" type="INTEGER" primaryKey="true" />
		<column name="EmployeeId" title="员工Id" type="INTEGER" />
		<column name="Name" title="名称" type="VARCHAR" size="64" />
		<column name="Relation" title="与本人关系" type="ENUM">
			<state value="10">父亲</state>
			<state value="20">母亲</state>
			<state value="30">公公</state>
			<state value="40">婆婆</state>
			<state value="50">儿子</state>
			<state value="60">女儿</state>
		</column>
		<column name="Phone" title="联系电话" type="VARCHAR" size="32" />
		<column name="IsDelete" title="是否删除" type="BOOLEAN" />
		<column name="createUser" title="创建人" type="VARCHAR" size="32" />
		<column name="createTime" title="创建时间" type="TIMESTAMP" />
		<column name="updateUser" title="更新人" type="VARCHAR" size="32" />
		<column name="updateTime" title="更新时间" type="TIMESTAMP" />
	</table>
	
	<table name="hr_employee_benefit" title="员工薪资福利" module="hr.employee" javaName="EmployeeBenefit" geometry="887,533,185,168" collapsed="false">
		<column name="Id" title="编号" type="INTEGER" primaryKey="true" />
		<column name="EmployeeId" title="员工Id" type="INTEGER" />
		<column name="PreTaxSalary" type="NUMBER" title="税前工资" size="20" scale="2"/>
		<column name="TrialPeriodSalary" type="NUMBER" title="试用期工资" size="20" scale="2"/>
		<column name="BankAccount" title="工资卡开户行" type="VARCHAR" size="64" />
		<column name="SalaryCardNo" title="工资卡号" type="VARCHAR" size="64" />
		<column name="ProvidentFundDepositBase" type="NUMBER" title="住房公积金缴存基数" size="20" scale="2"/>
		<column name="InsureDepositBase" type="NUMBER" title="保险缴存基数" size="20" scale="2"/>
		<column name="PayDate" title="起缴日期" type="DATE" />
		<column name="createUser" title="创建人" type="VARCHAR" size="32" />
		<column name="createTime" title="创建时间" type="TIMESTAMP" />
		<column name="updateUser" title="更新人" type="VARCHAR" size="32" />
		<column name="updateTime" title="更新时间" type="TIMESTAMP" />
	</table>
